// SET THESE AFTER DEPLOYING BANK FACTORY AND PROJECT FACTORY CONTRACTS
// DO NOT SET TO WALLET ADDRESSES, INDIVIDUAL MANAGERS ARE STORED IN THE
// CONTRACTS.

const constants = {
  DEFAULT_BANK_ADDRESS: "0xBcFaF4dBa57E5c9B4b37F732fae161326E8682d0"
};

module.exports = constants;
